### ISSUE TITLE
`lexicon.json` not found.

### ISSUE THREAD

**Issue by tae898** [leolani/cltl-chatbots#14]
```console
(leolani) ➜  cltl-chatbots git:(main) python src/chatbots/bots/episodic_text_memory.py
/home/tk/.virtualenvs/leolani/lib/python3.8/site-packages/rdflib_jsonld/__init__.py:9: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.1.  Please remove rdflib-jsonld from your project's dependencies.
  warnings.warn(
[nltk_data] Downloading package punkt to /home/tk/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Traceback (most recent call last):
  File "src/chatbots/bots/episodic_text_memory.py", line 6, in <module>
    from cltl.triple_extraction.api import Chat
  File "/home/tk/.virtualenvs/leolani/lib/python3.8/site-packages/cltl/triple_extraction/api.py", line 15, in <module>
    from cltl.triple_extraction.analyzer import Analyzer
  File "/home/tk/.virtualenvs/leolani/lib/python3.8/site-packages/cltl/triple_extraction/analyzer.py", line 4, in <module>
    from cltl.triple_extraction.utils.helper_functions import *
  File "/home/tk/.virtualenvs/leolani/lib/python3.8/site-packages/cltl/triple_extraction/utils/helper_functions.py", line 19, in <module>
    lexicon = json.load(open(os.path.join(ROOT, 'data', 'lexicon.json')))
FileNotFoundError: [Errno 2] No such file or directory: '/home/tk/.virtualenvs/leolani/lib/python3.8/site-packages/cltl/triple_extraction/utils/../data/lexicon.json'
```

**Comment by tae898** [comment]
I tried several hacks (e.g., copying the `lexicon.json` in to the directory where it's expected), but it causes more errors.
This should be fixed in a right way.
