### ISSUE TITLE
Can't install due to cltl.triple_extraction UnicodeDecodeError

### ISSUE THREAD

**Issue by a-r-t-i-f-i-c-i-a-l** [leolani/cltl-chatbots#3]
When trying to install `cltl-chatbots` with `py -m pip install -r requirements.txt`, I get the following output:
```
Collecting cltl.brain
  Using cached cltl.brain-0.0.dev7.tar.gz (253 kB)
Collecting cltl.asr[impl]
  Using cached cltl.asr-0.0.dev5.tar.gz (5.1 kB)
Collecting cltl.vad[impl]
  Using cached cltl.vad-0.0.dev1.tar.gz (5.6 kB)
Collecting cltl.backend[host,impl]
  Using cached cltl.backend-0.0.dev1.tar.gz (11 kB)
Collecting cltl.reply-generation
  Using cached cltl.reply_generation-0.0.dev8.tar.gz (20 kB)
Collecting cltl.triple-extraction
  Using cached cltl.triple_extraction-0.0.dev3.tar.gz (82.8 MB)
    ERROR: Command errored out with exit status 1:
     command: '(...)\cltl-chatbots\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\...\\AppData\\Local\\Temp\\pip-install-wv1monyx\\cltl-triple-extraction_0bf0c5efb60442338d7916b55f661f41\\setup.py'"'"'; __file__='"'"'C:\\Users\\...\\AppData\\Local\\Temp\\pip-install-wv1monyx\\cltl-triple-extraction_0bf0c5efb60442338d7916b55f661f41\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\...\AppData\Local\Temp\pip-pip-egg-info-zg6zfxj_'
         cwd: C:\Users\...\AppData\Local\Temp\pip-install-wv1monyx\cltl-triple-extraction_0bf0c5efb60442338d7916b55f661f41\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\...\AppData\Local\Temp\pip-install-wv1monyx\cltl-triple-extraction_0bf0c5efb60442338d7916b55f661f41\setup.py", line 4, in <module>
        long_description = fh.read()
      File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1390: character maps to <undefined>
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/38/20/3f597645c874ec9ae57315d9e6009e22b767bb1ca90e113a980e8b40557c/cltl.triple_extraction-0.0.dev3.tar.gz#sha256=8cb45ce3ac544d663548236c6aa473fbf1b4372d3c8adb2d3cbbbf754a029c1e (from https://pypi.org/simple/cltl-triple-extraction/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement cltl.triple-extraction (from versions: 0.0.dev3)
ERROR: No matching distribution found for cltl.triple-extraction```

**Comment by tae898** [comment]
Hey,

I guess you are using a Windows machine.
Unfortunately, I haven't tested anything on Windows, so I can't help with you so much at this moment.

Btw, running Linux on Windows has become much simpler:
1. https://docs.microsoft.com/en-us/windows/wsl/install 
2. https://opensource.com/article/18/5/dual-boot-linux

It's of course a pain in the ass to move from Windows to Linux, but I bet it's worth it, especially if you are willing to be involved more into software development.

Otherwise, you'll have to google or find someone who can help you with running things on a Windows machine.

**Comment by tae898** [comment]
@a-r-t-i-f-i-c-i-a-l 

One of the students managed to run it on Windows.
Check this out: https://github.com/leolani/cltl-chatbots/blob/main/TROUBLESHOOTING.md

**Comment by a-r-t-i-f-i-c-i-a-l** [comment]
I've tried the steps outlined there, but the encoding is already set in `setup.py`. Trying to change it to `# encoding: utf-8` does nothing either.

**Comment by tae898** [comment]
Do you wanna give a shot at windows 11 WSL?
I've tested it yesterday, and now it supports sound output as well. They say USB devices might work too but it might be a bit hacky at this point.
